[package]
name                   = "ruf"
version                = "0.0.1"
edition                = "2021"

authors                = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
description            = "Rust FORTH"
